//! Environment state snapshots and the comparison between two of them.
//!
//! `clio save-state <file> -e <env>` writes the whole configuration of an
//! environment as YAML: enabled features, system setting values, registered web
//! services, and every package with a hash per package and per schema. That one
//! file is the entire data source for comparing two environments — no other
//! command is needed, and nothing here parses CLI prose.
//!
//! **The parser is deliberately narrow.** The document is machine-generated by
//! clio in four fixed shapes, verified across a real 986 KB capture containing
//! no block scalars, no anchors and no flow collections. A general YAML crate
//! would be a heavier dependency than the job needs — and the only maintained
//! options are forks of a deprecated one, which is a poor trade in a path that
//! handles credentials. If clio's output ever grows a construct below, this
//! parser must be replaced rather than patched.
//!
//! **Snapshots contain live secrets.** Setting values are stored verbatim,
//! including API keys and passwords (see the handoff). Nothing in this module
//! may log a value, and callers must mask by default.

use crate::jobs::JobState;
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::time::UNIX_EPOCH;
use tauri::{AppHandle, Manager, State};

#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct EnvState {
    /// Feature code → the enabled state per audience, rendered canonically.
    pub features: BTreeMap<String, String>,
    /// Setting code → value.
    pub settings: BTreeMap<String, String>,
    /// Web service name → url.
    pub webservices: BTreeMap<String, String>,
    /// Package name → its hash, maintainer and schema hashes.
    pub packages: BTreeMap<String, PackageState>,
}

#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PackageState {
    pub hash: String,
    pub maintainer: String,
    /// Schema name → hash. Present only for packages clio reported schemas for.
    pub schemas: BTreeMap<String, String>,
}

/// Strip the quoting clio applies to scalars that need it, e.g. `'{0}'`.
fn unquote(value: &str) -> String {
    let value = value.trim();
    if value.len() >= 2 && value.starts_with('\'') && value.ends_with('\'') {
        return value[1..value.len() - 1].replace("''", "'");
    }
    if value.len() >= 2 && value.starts_with('"') && value.ends_with('"') {
        return value[1..value.len() - 1].replace("\\\"", "\"");
    }
    value.to_string()
}

/// Split `key: value` at the **first** colon.
///
/// Values routinely contain colons — every URL does — while clio's keys never
/// do, so splitting at the first is both correct and unambiguous.
fn split_pair(line: &str) -> Option<(String, String)> {
    let (key, value) = line.split_once(':')?;
    Some((key.trim().to_string(), unquote(value)))
}

/// Parse a `save-state` document.
///
/// Unknown sections and unrecognised lines are skipped rather than failing: a
/// future clio adding a fifth section should not make the whole comparison
/// unavailable.
pub fn parse_state(raw: &str) -> EnvState {
    let mut state = EnvState::default();
    let mut section = String::new();
    // The entry currently being assembled, plus the package name for schema
    // rows, which arrive indented beneath their package.
    let mut entry: BTreeMap<String, String> = BTreeMap::new();
    let mut audiences: BTreeMap<String, String> = BTreeMap::new();
    let mut package: Option<String> = None;
    let mut in_schemas = false;

    /// Commit whatever entry has been accumulated into the state.
    fn flush(
        state: &mut EnvState,
        section: &str,
        entry: &mut BTreeMap<String, String>,
        audiences: &mut BTreeMap<String, String>,
        package: &mut Option<String>,
    ) {
        match section {
            "features" => {
                if let Some(code) = entry.get("code") {
                    // "All employees=true; All external users=false" — sorted by
                    // BTreeMap so two environments always render comparably.
                    let rendered = audiences
                        .iter()
                        .map(|(who, value)| format!("{who}={value}"))
                        .collect::<Vec<_>>()
                        .join("; ");
                    state.features.insert(code.clone(), rendered);
                }
            }
            "settings" => {
                if let Some(code) = entry.get("code") {
                    state
                        .settings
                        .insert(code.clone(), entry.get("value").cloned().unwrap_or_default());
                }
            }
            "webservices" => {
                if let Some(name) = entry.get("name") {
                    state
                        .webservices
                        .insert(name.clone(), entry.get("url").cloned().unwrap_or_default());
                }
            }
            "packages" => {
                if let Some(name) = entry.get("name") {
                    let existing = state.packages.entry(name.clone()).or_default();
                    existing.hash = entry.get("hash").cloned().unwrap_or_default();
                    existing.maintainer = entry.get("maintainer").cloned().unwrap_or_default();
                    *package = Some(name.clone());
                }
            }
            _ => {}
        }
        entry.clear();
        audiences.clear();
    }

    for line in raw.lines() {
        if line.trim().is_empty() {
            continue;
        }
        let indent = line.len() - line.trim_start().len();
        let trimmed = line.trim();

        // A new top-level section.
        if indent == 0 && !trimmed.starts_with('-') && trimmed.ends_with(':') {
            flush(&mut state, &section, &mut entry, &mut audiences, &mut package);
            section = trimmed.trim_end_matches(':').to_string();
            package = None;
            in_schemas = false;
            continue;
        }

        // A new list entry at the top level closes the previous one.
        if indent == 0 && trimmed.starts_with("- ") {
            flush(&mut state, &section, &mut entry, &mut audiences, &mut package);
            in_schemas = false;
            if let Some((key, value)) = split_pair(trimmed.trim_start_matches("- ")) {
                // A package owns the schema rows that follow it, which arrive
                // long before this entry is flushed — so claim the name now.
                if section == "packages" && key == "name" {
                    state.packages.entry(value.clone()).or_default();
                    package = Some(value.clone());
                }
                entry.insert(key, value);
            }
            continue;
        }

        // A schema row: `  - name: X` then `    hash: Y`, nested under a package.
        if in_schemas && trimmed.starts_with("- ") {
            if let Some((key, value)) = split_pair(trimmed.trim_start_matches("- ")) {
                if key == "name" {
                    entry.insert("__schema".into(), value);
                }
            }
            continue;
        }

        let Some((key, value)) = split_pair(trimmed) else { continue };

        // `schemas:` and `users_values:` open a nested block with no value.
        if value.is_empty() {
            in_schemas = key == "schemas";
            continue;
        }

        if in_schemas && key == "hash" {
            if let (Some(package_name), Some(schema)) =
                (package.as_ref(), entry.get("__schema").cloned())
            {
                state
                    .packages
                    .entry(package_name.clone())
                    .or_default()
                    .schemas
                    .insert(schema, value);
            }
            continue;
        }

        // Indented under a feature entry, anything that is not a known field is
        // an audience name.
        if section == "features" && indent >= 4 {
            audiences.insert(key, value);
            continue;
        }

        entry.insert(key, value);
    }
    flush(&mut state, &section, &mut entry, &mut audiences, &mut package);
    state
}

// ---------------------------------------------------------------- comparison

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DiffRow {
    /// `package` | `setting` | `feature` | `webservice` | `schema`
    pub category: String,
    pub key: String,
    /// `None` means absent on that side, which is different from an empty value.
    pub source: Option<String>,
    pub target: Option<String>,
    /// `same` | `different` | `missingTarget` | `missingSource`
    pub status: String,
    /// The code looks like a credential. A hint for warning copy only — the UI
    /// masks every setting value regardless.
    pub sensitive: bool,
    /// Schema-level rows, for packages whose hash differs.
    pub detail: Vec<DiffRow>,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DiffReport {
    pub source_env: String,
    pub target_env: String,
    pub source_captured_at: u64,
    pub target_captured_at: u64,
    pub rows: Vec<DiffRow>,
    /// Differing rows per category, for the tab badges.
    pub counts: BTreeMap<String, usize>,
}

/// Whether a setting code looks like it holds a credential.
///
/// A hint, never a boundary. Creatio's own `SysSettings.ValueTypeName =
/// 'SecureText'` marking is not in the state file at all, and is incomplete
/// anyway — `FacebookConsumerSecret` and `mandrillApiKey` are plain text types.
/// See the handoff. Everything is masked by default; this only decides where an
/// extra warning appears.
pub fn looks_sensitive(code: &str) -> bool {
    const NEEDLES: [&str; 8] = [
        "key", "secret", "password", "token", "auth", "jwk", "credential", "licen",
    ];
    let lower = code.to_lowercase();
    NEEDLES.iter().any(|needle| lower.contains(needle))
}

fn compare_maps(
    category: &str,
    source: &BTreeMap<String, String>,
    target: &BTreeMap<String, String>,
    sensitive: bool,
) -> Vec<DiffRow> {
    let mut keys: Vec<&String> = source.keys().chain(target.keys()).collect();
    keys.sort();
    keys.dedup();
    keys.into_iter()
        .map(|key| {
            let left = source.get(key).cloned();
            let right = target.get(key).cloned();
            DiffRow {
                category: category.to_string(),
                key: key.clone(),
                status: status_of(&left, &right).to_string(),
                sensitive: sensitive && looks_sensitive(key),
                source: left,
                target: right,
                detail: Vec::new(),
            }
        })
        .collect()
}

fn status_of(source: &Option<String>, target: &Option<String>) -> &'static str {
    match (source, target) {
        (Some(left), Some(right)) if left == right => "same",
        (Some(_), Some(_)) => "different",
        (Some(_), None) => "missingTarget",
        (None, Some(_)) => "missingSource",
        (None, None) => "same",
    }
}

/// Compare two captured states.
///
/// Every key from either side appears exactly once; the caller filters to
/// differences. Packages carry schema-level children so a version-identical
/// package with a changed schema is still visible — that is the collision the
/// roadmap wanted caught before deployment.
pub fn diff_states(source: &EnvState, target: &EnvState) -> Vec<DiffRow> {
    let mut rows = Vec::new();
    rows.extend(compare_maps("feature", &source.features, &target.features, false));
    rows.extend(compare_maps("setting", &source.settings, &target.settings, true));
    rows.extend(compare_maps(
        "webservice",
        &source.webservices,
        &target.webservices,
        false,
    ));

    let mut names: Vec<&String> = source.packages.keys().chain(target.packages.keys()).collect();
    names.sort();
    names.dedup();
    for name in names {
        let left = source.packages.get(name);
        let right = target.packages.get(name);
        let left_hash = left.map(|package| package.hash.clone());
        let right_hash = right.map(|package| package.hash.clone());
        let status = status_of(&left_hash, &right_hash);

        let detail = if status == "different" {
            let empty = BTreeMap::new();
            compare_maps(
                "schema",
                left.map(|p| &p.schemas).unwrap_or(&empty),
                right.map(|p| &p.schemas).unwrap_or(&empty),
                false,
            )
            .into_iter()
            .filter(|row| row.status != "same")
            .collect()
        } else {
            Vec::new()
        };

        rows.push(DiffRow {
            category: "package".to_string(),
            key: name.clone(),
            // The maintainer travels with the row so the table can show who owns
            // a package that exists on only one side.
            source: left.map(|package| package.maintainer.clone()).filter(|m| !m.is_empty()),
            target: right.map(|package| package.maintainer.clone()).filter(|m| !m.is_empty()),
            status: status.to_string(),
            sensitive: false,
            detail,
        });
    }
    rows
}

/// Differing rows per category, for the tab badges.
pub fn count_differences(rows: &[DiffRow]) -> BTreeMap<String, usize> {
    let mut counts = BTreeMap::new();
    for row in rows.iter().filter(|row| row.status != "same") {
        *counts.entry(row.category.clone()).or_insert(0) += 1;
    }
    counts
}

// ------------------------------------------------------------ snapshot store

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SnapshotInfo {
    pub env: String,
    pub captured_at: u64,
    pub size_bytes: u64,
    /// How long the last successful capture of this environment took.
    ///
    /// Recorded because the spread is large and not guessable: a local IIS
    /// install answers in about two minutes, a cloud tenant takes considerably
    /// longer. Showing the previous real duration beats any built-in estimate.
    /// `0` means this environment has not been captured yet.
    pub duration_ms: u64,
}

/// Sidecar holding per-environment capture durations, next to the snapshots.
fn durations_file(app: &AppHandle) -> Result<PathBuf, String> {
    Ok(snapshot_dir(app)?.join("durations.json"))
}

fn read_durations(app: &AppHandle) -> BTreeMap<String, u64> {
    durations_file(app)
        .ok()
        .and_then(|path| std::fs::read_to_string(path).ok())
        .and_then(|json| serde_json::from_str(&json).ok())
        .unwrap_or_default()
}

fn record_duration(app: &AppHandle, env: &str, elapsed_ms: u64) {
    let mut all = read_durations(app);
    all.insert(env.to_string(), elapsed_ms);
    if let (Ok(path), Ok(json)) = (durations_file(app), serde_json::to_string_pretty(&all)) {
        let _ = std::fs::write(path, json);
    }
}

/// Where captured states live. Separate from `catalog-cache.json` on purpose:
/// that file holds only names and versions, whereas these hold setting values
/// — credentials included — so they are kept apart, listed, and deletable.
fn snapshot_dir(app: &AppHandle) -> Result<PathBuf, String> {
    let dir = app
        .path()
        .app_data_dir()
        .map_err(|error| format!("No application data directory: {error}"))?
        .join("snapshots");
    std::fs::create_dir_all(&dir).map_err(|error| format!("Could not create {dir:?}: {error}"))?;
    Ok(dir)
}

/// One file per environment. Environment names come from clio's registry and
/// may contain characters a file name cannot, so anything outside a safe set is
/// replaced rather than trusted.
fn snapshot_path(app: &AppHandle, env: &str) -> Result<PathBuf, String> {
    let safe: String = env
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() || c == '-' || c == '_' { c } else { '_' })
        .collect();
    if safe.is_empty() {
        return Err("Select an environment first.".to_string());
    }
    Ok(snapshot_dir(app)?.join(format!("{safe}.yaml")))
}

fn modified_ms(path: &Path) -> u64 {
    std::fs::metadata(path)
        .and_then(|meta| meta.modified())
        .ok()
        .and_then(|time| time.duration_since(UNIX_EPOCH).ok())
        .map(|since| since.as_millis() as u64)
        .unwrap_or(0)
}

#[tauri::command]
pub fn list_snapshots(app: AppHandle) -> Result<Vec<SnapshotInfo>, String> {
    let dir = snapshot_dir(&app)?;
    let durations = read_durations(&app);
    let mut found = Vec::new();
    for entry in std::fs::read_dir(&dir).map_err(|error| error.to_string())?.flatten() {
        let path = entry.path();
        if path.extension().and_then(|ext| ext.to_str()) != Some("yaml") {
            continue;
        }
        let Some(stem) = path.file_stem().and_then(|stem| stem.to_str()) else { continue };
        found.push(SnapshotInfo {
            env: stem.to_string(),
            captured_at: modified_ms(&path),
            size_bytes: entry.metadata().map(|meta| meta.len()).unwrap_or(0),
            duration_ms: durations.get(stem).copied().unwrap_or(0),
        });
    }
    found.sort_by(|a, b| a.env.to_lowercase().cmp(&b.env.to_lowercase()));
    Ok(found)
}

#[tauri::command]
pub fn delete_snapshot(app: AppHandle, env: String) -> Result<(), String> {
    let path = snapshot_path(&app, &env)?;
    if path.exists() {
        std::fs::remove_file(&path)
            .map_err(|error| format!("Could not delete the snapshot: {error}"))?;
    }
    Ok(())
}

/// Capture an environment's full state.
///
/// Runs as a job because it takes minutes — roughly two against dev-834 and
/// longer over the network. It is **read-only**, so the whole run is
/// cancellable, unlike the deployment jobs.
#[tauri::command]
pub fn capture_env_state(
    app: AppHandle,
    jobs: State<'_, JobState>,
    env: String,
) -> Result<String, String> {
    let env = env.trim().to_string();
    let path = snapshot_path(&app, &env)?;
    let id = jobs.create_job(
        &app,
        "capture-state",
        Some(env.clone()),
        format!("capture state of {env}"),
    );
    let lock = jobs.env_lock(Some(&env));
    let state = jobs.inner().clone();
    let job_id = id.clone();
    std::thread::spawn(move || {
        let _guard = lock.lock().unwrap();
        if !state.mark_running_phase(&app, &job_id, "reading environment state", true) {
            return;
        }
        let started = std::time::Instant::now();
        // No `--overwrite`: it is a switch that already defaults to true, and
        // passing a value made clio consume `true` as the next positional and
        // report `Active environment 'true' is not found`.
        let args = vec![
            "save-state".to_string(),
            path.to_string_lossy().to_string(),
            "-e".to_string(),
            env.clone(),
        ];
        match state.stream_process(&app, &job_id, "clio", &args, None, &[]) {
            Ok(code) => {
                if code == 0 && !path.exists() {
                    state.log(
                        &app,
                        &job_id,
                        "clio reported success but wrote no state file.".to_string(),
                    );
                    state.finish(&app, &job_id, Some(1));
                    return;
                }
                if code == 0 {
                    record_duration(&app, &env, started.elapsed().as_millis() as u64);
                    state.log(
                        &app,
                        &job_id,
                        "This snapshot contains system setting values, including any \
                         credentials held in settings. Delete it from the Compare screen \
                         when finished."
                            .to_string(),
                    );
                }
                state.finish(&app, &job_id, Some(code));
            }
            Err(error) => {
                state.log(&app, &job_id, error);
                state.finish(&app, &job_id, Some(1));
            }
        }
    });
    Ok(id)
}

fn read_state(app: &AppHandle, env: &str) -> Result<(EnvState, u64), String> {
    let path = snapshot_path(app, env)?;
    let raw = std::fs::read_to_string(&path).map_err(|_| {
        format!("No snapshot of {env} yet — capture it first.")
    })?;
    Ok((parse_state(&raw), modified_ms(&path)))
}

/// Compare two captured environments.
///
/// Reads only from disk: comparing is instant, and re-comparing never re-reads
/// the environments. Whether a snapshot is stale is the user's call, which is
/// why both capture times travel with the report.
#[tauri::command]
pub fn diff_environments(
    app: AppHandle,
    source_env: String,
    target_env: String,
) -> Result<DiffReport, String> {
    if source_env.trim() == target_env.trim() {
        return Err("Choose two different environments to compare.".to_string());
    }
    let (source, source_captured_at) = read_state(&app, &source_env)?;
    let (target, target_captured_at) = read_state(&app, &target_env)?;
    let rows = diff_states(&source, &target);
    Ok(DiffReport {
        source_env,
        target_env,
        source_captured_at,
        target_captured_at,
        counts: count_differences(&rows),
        rows,
    })
}

/// Render a comparison as markdown for sharing.
///
/// **Setting values are never included.** The roadmap wanted this pasted into
/// Slack when escalating to Creatio support, and setting values are exactly
/// where API keys live — so a setting row states only that it differs. Package
/// and feature rows carry their values, which are hashes and booleans.
pub fn render_report(report: &DiffReport) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "# {} vs {}\n\n",
        report.source_env, report.target_env
    ));
    out.push_str(
        "Setting values are omitted deliberately: they can contain API keys and passwords.\n\n",
    );

    for (category, label) in [
        ("package", "Packages"),
        ("setting", "System settings"),
        ("feature", "Features"),
        ("webservice", "Web services"),
    ] {
        let rows: Vec<&DiffRow> = report
            .rows
            .iter()
            .filter(|row| row.category == category && row.status != "same")
            .collect();
        if rows.is_empty() {
            continue;
        }
        out.push_str(&format!("## {label} ({} differing)\n\n", rows.len()));
        out.push_str(&format!("| Item | {} | {} |\n|---|---|---|\n", report.source_env, report.target_env));
        for row in rows {
            let cell = |value: &Option<String>| match value {
                None => "—".to_string(),
                Some(_) if category == "setting" => "set".to_string(),
                Some(value) if value.is_empty() => "(empty)".to_string(),
                Some(value) => value.clone(),
            };
            out.push_str(&format!(
                "| {} | {} | {} |\n",
                row.key,
                cell(&row.source),
                cell(&row.target)
            ));
        }
        out.push('\n');
    }
    if report.counts.is_empty() {
        out.push_str("No differences found.\n");
    }
    out
}

#[tauri::command]
pub fn export_diff_report(
    app: AppHandle,
    source_env: String,
    target_env: String,
    path: String,
) -> Result<(), String> {
    let report = diff_environments(app, source_env, target_env)?;
    std::fs::write(&path, render_report(&report))
        .map_err(|error| format!("Could not write the report: {error}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Shapes taken verbatim from a real dev-834 capture.
    const CAPTURE: &str = "\
features:
- code: AllowUseAdvancedMacros
  users_values:
    All employees: true
- code: AttachedImages
  users_values:
    All employees: true
    All external users: false
settings:
- code: AccountCodeMask
  value: '{0}'
- code: AccountEnrichmentServiceUrl
  value: https://demo-enrichment.bpmonline.com
- code: AccountLastNumber
  value: 128
webservices:
- url: https://generativelanguage.googleapis.com/
  name: GeminiApiSearch
packages:
- name: ActionsDashboard
  hash: 154BFC485C4B0D9D04D6CB75684D8C3D
  maintainer: Creatio
  schemas:
  - name: ActionDashboardComponent
    hash: 55D391E8405FD7A3C8DBE3B81AD86D42
  - name: ActionsDashboardCSS
    hash: 997FD982D20CE4F0726F8F6FC9C1F756
- name: QntProjectHub
  hash: AAAA1111
  maintainer: Qnovate
";

    #[test]
    fn parses_every_section_of_a_real_capture() {
        let state = parse_state(CAPTURE);

        assert_eq!(state.features.len(), 2);
        assert_eq!(state.features["AllowUseAdvancedMacros"], "All employees=true");
        assert_eq!(
            state.features["AttachedImages"],
            "All employees=true; All external users=false"
        );

        assert_eq!(state.settings.len(), 3);
        // Quoting removed, and a value containing "://" survives intact.
        assert_eq!(state.settings["AccountCodeMask"], "{0}");
        assert_eq!(
            state.settings["AccountEnrichmentServiceUrl"],
            "https://demo-enrichment.bpmonline.com"
        );

        assert_eq!(state.webservices["GeminiApiSearch"], "https://generativelanguage.googleapis.com/");

        assert_eq!(state.packages.len(), 2);
        let dashboard = &state.packages["ActionsDashboard"];
        assert_eq!(dashboard.hash, "154BFC485C4B0D9D04D6CB75684D8C3D");
        assert_eq!(dashboard.maintainer, "Creatio");
        assert_eq!(dashboard.schemas.len(), 2);
        assert_eq!(
            dashboard.schemas["ActionDashboardComponent"],
            "55D391E8405FD7A3C8DBE3B81AD86D42"
        );
        // A package with no schemas block must not inherit the previous one's.
        assert!(state.packages["QntProjectHub"].schemas.is_empty());
        assert_eq!(state.packages["QntProjectHub"].maintainer, "Qnovate");
    }

    #[test]
    fn tells_absent_apart_from_changed() {
        let source = parse_state(CAPTURE);
        let mut target = parse_state(CAPTURE);
        target.settings.insert("AccountLastNumber".into(), "999".into());
        target.settings.remove("AccountCodeMask");
        target.settings.insert("BrandNew".into(), "1".into());

        let rows = diff_states(&source, &target);
        let find = |key: &str| {
            rows.iter()
                .find(|row| row.category == "setting" && row.key == key)
                .expect("setting row")
        };
        assert_eq!(find("AccountLastNumber").status, "different");
        assert_eq!(find("AccountCodeMask").status, "missingTarget");
        assert_eq!(find("BrandNew").status, "missingSource");
        assert_eq!(find("AccountEnrichmentServiceUrl").status, "same");
    }

    #[test]
    fn a_changed_schema_shows_under_its_package() {
        let source = parse_state(CAPTURE);
        let mut target = parse_state(CAPTURE);
        let package = target.packages.get_mut("ActionsDashboard").unwrap();
        package.hash = "DIFFERENT".into();
        package.schemas.insert("ActionsDashboardCSS".into(), "CHANGED".into());

        let rows = diff_states(&source, &target);
        let dashboard = rows
            .iter()
            .find(|row| row.category == "package" && row.key == "ActionsDashboard")
            .expect("package row");
        assert_eq!(dashboard.status, "different");
        // Only the schema that moved, not all of them.
        assert_eq!(dashboard.detail.len(), 1);
        assert_eq!(dashboard.detail[0].key, "ActionsDashboardCSS");
        assert_eq!(dashboard.detail[0].status, "different");
    }

    #[test]
    fn identical_environments_report_no_differences() {
        let state = parse_state(CAPTURE);
        let rows = diff_states(&state, &state);
        assert!(rows.iter().all(|row| row.status == "same"));
        assert!(count_differences(&rows).is_empty());
    }

    #[test]
    fn credential_shaped_setting_codes_are_flagged() {
        // Verified live: these carry ordinary text types in SysSettings, so the
        // platform's own SecureText marking would have missed them.
        for code in [
            "FacebookConsumerSecret",
            "mandrillApiKey",
            "LDAPServerPassword",
            "IdentityAssertionIssuerPrivateJwk",
            "ApryseLicenseKey",
        ] {
            assert!(looks_sensitive(code), "{code} should be flagged");
        }
        assert!(!looks_sensitive("AccountLastNumber"));
    }

    #[test]
    fn an_unknown_section_does_not_break_the_rest() {
        let raw = "settings:\n- code: A\n  value: 1\nnewthing:\n- code: X\n  value: 2\n";
        let state = parse_state(raw);
        assert_eq!(state.settings["A"], "1");
        assert_eq!(state.settings.len(), 1);
    }
}
